"""
One-shot helper (run from the fase-2.5 branch) that materializes
paper/audit_outputs/exp8_stats_phase2_5.csv from the regenerated
experiments/results/exp8/retrieval_metrics.json.

This is a build step, not a runtime artifact. Kept under scripts/audit
so the CSV itself is traceable back to deterministic JSON inputs and
exact formulas, but it is NOT imported from anywhere else.

Columns match the m16 exp8_stats_corrected.csv schema plus the new
Phase 1 BH/Holm/d_z fields, so a reviewer can diff them row-by-row.

Run once:
    python scripts/audit/_write_phase2_5_csv.py
"""

import csv
import json
import math
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC_JSON = REPO_ROOT / "experiments" / "results" / "exp8" / "retrieval_metrics.json"
OUT_CSV = REPO_ROOT / "paper" / "audit_outputs" / "exp8_stats_phase2_5.csv"


def effect_label(abs_d: float) -> str:
    if abs_d < 0.2:
        return "negligible"
    if abs_d < 0.5:
        return "small"
    if abs_d < 0.8:
        return "medium"
    return "large"


def derive_r_and_alt_ds(mean_a, mean_b, std_a, std_b, d_z):
    """Back-derive the paired correlation r from (d_z, mean_diff, std_a, std_b)
    and compute d_av and d_rm per Lakens 2013.

    d_z      = mean_diff / std_diff
    std_diff = |mean_diff / d_z|  (when d_z != 0)
    r        = (std_a^2 + std_b^2 - std_diff^2) / (2 * std_a * std_b)
    d_av     = mean_diff / ((std_a + std_b) / 2)
    d_rm     = d_z * sqrt(2 * (1 - r))
    """
    mean_diff = mean_b - mean_a
    if abs(d_z) < 1e-12:
        return {"r": None, "d_av": None, "d_rm": None, "std_diff": None}
    std_diff = mean_diff / d_z
    denom = 2.0 * std_a * std_b
    if denom == 0:
        r = None
    else:
        r = (std_a * std_a + std_b * std_b - std_diff * std_diff) / denom
    d_av_denom = (std_a + std_b) / 2.0
    d_av = mean_diff / d_av_denom if d_av_denom > 0 else None
    d_rm = (d_z * math.sqrt(2.0 * (1.0 - r))) if (r is not None and r <= 1.0) else None
    return {"r": r, "d_av": d_av, "d_rm": d_rm, "std_diff": std_diff}


def main() -> None:
    doc = json.loads(SRC_JSON.read_text(encoding="utf-8"))
    stats = doc["statistical_tests"]

    fieldnames = [
        "metric",
        "system_a",
        "system_b",
        "pair",
        "n",
        "mean_a",
        "mean_b",
        "std_a",
        "std_b",
        "mean_diff_b_minus_a",
        "std_diff_derived",
        "r_derived",
        "cohens_d_z",
        "d_av_derived",
        "d_rm_derived",
        "d_z_label",
        "p_raw",
        "p_bh",
        "sig_bh",
        "p_holm",
        "sig_holm",
        "correction_family_size",
        "ci_95_lower",
        "ci_95_upper",
        "test",
        "significant_raw",
        "meets_thresh_d_z",
    ]

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)

    rows = []
    # Preserve the order m16 used: metric x (BM25 vs Dense, BM25 vs Hibrido,
    # Dense vs Hibrido) for every metric. statistical_tests dict already
    # iterates in insertion order.
    for metric, by_pair in stats.items():
        for pair, leaf in by_pair.items():
            mean_a = float(leaf["mean_a"])
            mean_b = float(leaf["mean_b"])
            std_a = float(leaf["std_a"])
            std_b = float(leaf["std_b"])
            d_z = float(leaf["cohens_d_z"])
            derived = derive_r_and_alt_ds(mean_a, mean_b, std_a, std_b, d_z)
            row = {
                "metric": metric,
                "system_a": leaf["system_a"],
                "system_b": leaf["system_b"],
                "pair": pair,
                "n": int(leaf["n"]),
                "mean_a": mean_a,
                "mean_b": mean_b,
                "std_a": std_a,
                "std_b": std_b,
                "mean_diff_b_minus_a": mean_b - mean_a,
                "std_diff_derived": derived["std_diff"],
                "r_derived": derived["r"],
                "cohens_d_z": d_z,
                "d_av_derived": derived["d_av"],
                "d_rm_derived": derived["d_rm"],
                "d_z_label": effect_label(abs(d_z)),
                "p_raw": float(leaf["p_raw"]),
                "p_bh": float(leaf["p_bh"]),
                "sig_bh": bool(leaf["sig_bh"]),
                "p_holm": float(leaf["p_holm"]),
                "sig_holm": bool(leaf["sig_holm"]),
                "correction_family_size": int(leaf["correction_family_size"]),
                "ci_95_lower": float(leaf["ci_95_lower"]),
                "ci_95_upper": float(leaf["ci_95_upper"]),
                "test": leaf["test"],
                "significant_raw": bool(leaf["significant"]),
                "meets_thresh_d_z": abs(d_z) >= 0.5,
            }
            rows.append(row)

    with OUT_CSV.open("w", encoding="utf-8", newline="") as fh:
        fh.write(
            "# Generated by scripts/recompute_retrieval_stats.py "
            "Phase 2.5 - supersedes exp8_stats_corrected.csv\n"
        )
        fh.write(
            "# Source JSON: experiments/results/exp8/retrieval_metrics.json\n"
        )
        fh.write(
            "# Correction family: 12 tests (4 metrics x 3 pairs), "
            "BH-FDR + Holm, alpha=0.05\n"
        )
        fh.write(
            "# cohens_d_z = mean_diff_b_minus_a / std_diff (paired, ddof=1); "
            "d_av / d_rm / r derived per Lakens 2013\n"
        )
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)

    print(f"Wrote {len(rows)} rows to {OUT_CSV}")


if __name__ == "__main__":
    main()
